# Generated by Django 5.2 on 2025-06-30 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles_app", "0002_article_image_comment"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name="article",
            name="category",
            field=models.ManyToManyField(to="articles_app.category"),
        ),
    ]
