# Generated by Django 5.2 on 2025-07-01 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles_app", "0003_category_article_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="slug",
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
