# Generated by Django 5.2 on 2025-07-05 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles_app", "0006_remove_comment_author_alter_comment_parent"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="comments_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="article",
            name="published_date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
