# Generated by Django 5.2 on 2025-07-06 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles_app", "0007_article_comments_count_alter_article_published_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="article",
            options={"ordering": ["-published_date"]},
        ),
        migrations.AlterField(
            model_name="article",
            name="category",
            field=models.ManyToManyField(
                related_name="articles", to="articles_app.category"
            ),
        ),
    ]
